switch to npm
neofinancial/eslint-config-neo pull request #18
Opened 2021-12-22 21:04 UTC by TimaJuma

2021-12-22 21:05 UTC, TimaJuma commented on package.json
> +    "npm": ">=8.0.0"
or `"npm": ">=8.3.0"` ?

2021-12-22 21:06 UTC, rogersnick commented on package.json
> +    "npm": ">=8.0.0"
Either is probably fine

2021-12-22 21:06 UTC, rogersnick approved these changes

2021-12-22 21:08 UTC, TimaJuma commented
Did not touch `README` as it refers to the installation of this library, or we can add additional commands for `npm` as well in the description

2021-12-22 21:22 UTC, iansu requested changes

2021-12-22 21:22 UTC, iansu commented on CHANGELOG.md
> +## 0.7.0 (December 22, 2021)
This doesn't need a version bump because there's nothing new to publish. It's just an internal change.

2021-12-22 21:39 UTC, rogersnick approved these changes

2021-12-23 00:45 UTC, iansu approved these changes

2021-12-23 00:48 UTC, merged