ENGDX-498 adds auto fix package and rules
neofinancial/eslint-config-neo pull request #38
Opened 2024-04-08 17:55 UTC by neo-antonio-canabrava

2024-04-08 22:32 UTC, neo-raul-ribeiro submitted a review, later dismissed

2024-04-09 15:48 UTC, ScottKayeNeo submitted a review, later dismissed
Neat!

2024-04-09 17:59 UTC, AdamTranquilla requested changes
This looks great but please read the [publishing section of the readme](https://github.com/neofinancial/eslint-config-neo?tab=readme-ov-file#publishing) (update the [changelog](https://github.com/neofinancial/eslint-config-neo/blob/master/CHANGELOG.md))

2024-04-09 21:13 UTC, AdamTranquilla approved these changes
😎 nice work!

2024-04-09 22:28 UTC, merged